### ISSUE TITLE
Lightning Gallery - engineering review [evidently-data-analysis component] 

### ISSUE THREAD

**Issue by manskx** [Nachimak28/evidently-data-analysis#1]
Thanks for submitting your component to Lightning Gallary.

Looks good, I like it :)) I have a few points that will be nice to address before the component is added to the gallery 

1- Inside the [component](https://github.com/Nachimak28/evidently-data-analysis/blob/main/evidently_data_analysis/component.py) could you add some comments and docstrings so users know how to use the component?

2- Could you add an e2e test for your example app as part of the CI ? You can get some inspiration from here: https://github.com/Lightning-AI/lightning/tree/master/tests/tests_app_examples

3- Do you plan to add more features from [evidently](https://github.com/evidentlyai/evidently) ?

4- Maybe you can pin the version of evidently in the [requirements](https://github.com/Nachimak28/evidently-data-analysis/blob/main/requirements.txt) in case a release that introduces some breaking changes ? 

If you have any questions, please reach out! we will be happy to assist you to land your component in the Lightning gallery.

cc: @Nachimak28 @zippeurfou

**Comment by Nachimak28** [comment]
Hi @manskx Thank you for reviewing the component and yes I shall definitely address and work on all the points you've mentioned, unfortunately after building the first working version, I contracted a viral infection and still recovering, so you might find this codebase in a less than ideal state. But, rest assured, I plan on fix up everything as per points you've mentioned asap.

**Comment by manskx** [comment]
> Hi @manskx Thank you for reviewing the component and yes I shall definitely address and work on all the points you've mentioned, unfortunately after building the first working version, I contracted a viral infection and still recovering, so you might find this codebase in a less than ideal state. But, rest assured, I plan on fix up everything as per points you've mentioned asap.

@Nachimak28 Sorry to hear that, hope you get well soon!

Let me know if I can help :)

**Comment by Nachimak28** [comment]
Hello @manskx 
I've made the necessary amends to the codebase as per the mentioned points and also tested out the component in the lightning cloud with help from @robert-s-lee 

Just to answer the points mentioned:
1 - Comments and Docstrings added
2 - Necessary tests added to test the behaviour of component for multiple plausible scenarios and all passing locally
3 - As of now Evidently only supports Classification and Regression but as more features come in, I shall keep this component updated 
4 - All dependencies in requirements are pinned to specific versions

The CI still fails because it needs some token which I believe will be added if accepted for the gallery

I think the component is now in a good state to be a part of the component gallery but if you still have any more suggestions or changes required, I'll be happy to do them

If the current codebase meets your requirements and would be considered ready for the component gallery I might still have to fill out the component publish form right with the latest commit hash ?

**Comment by manskx** [comment]
Thanks @Nachimak28 this is awesome!
Yeah, a new recent hash is needed to publish the recent component updates.

**Comment by manskx** [comment]
@Nachimak28 would you mind submitting the component again? 
cc: @lantiga

**Comment by Nachimak28** [comment]
> @Nachimak28 would you mind submitting the component again? cc: @lantiga

Sorry I forgot to reply here, did it the moment I received your first reply in [this](https://lightning-ai.typeform.com/to/J4ORMSn8?typeform-source=jksfmy97iql.typeform.com) form about 2 hours ago. If I need to update it anywhere else too, please do let me know and I'll do it right away.

**Comment by manskx** [comment]
Thanks ! that should be good :)
